CREATE TABLE a(i TEXT PRIMARY KEY,n TEXT NOT NULL,u TEXT NOT NULL,d TEXT NOT NULL);
CREATE TABLE b(i INTEGER PRIMARY KEY,t INTEGER NOT NULL,n TEXT NOT NULL,b TEXT NOT NULL,c INTEGER NOT NULL);
CREATE TABLE c(i INTEGER PRIMARY KEY,t INTEGER NOT NULL,p INTEGER NOT NULL,a TEXT NOT NULL,b TEXT NOT NULL UNIQUE);