bind="0.0.0.0:80"
backlog=2048
workers=1
worker_class="sync"
worker_connections=1000
timeout=30
spew=False
errorlog="-"
accesslog="-"
loglevel="info"  
access_log_format='%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'